name: npm-publish
on:
  push:
    branches:
      - master # On push to master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12.16.0 # Node version indicated in package.json
      - run: npm install
      - run: npm test # Make sure tests pass before pushing to npm
      - uses: JS-DevTools/npm-publish@v1 # Push to npm if version has changed
        with:
          token: ${{ secrets.CHRIS_NPM_TOKEN }}
